//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratories.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Item {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Item() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Laboratories.Web.Resources.Item", typeof(Item).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biology.
        /// </summary>
        public static string biology {
            get {
                return ResourceManager.GetString("biology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemistry.
        /// </summary>
        public static string chemics {
            get {
                return ResourceManager.GetString("chemics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry year.
        /// </summary>
        public static string completionYear {
            get {
                return ResourceManager.GetString("completionYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Damaged OR Consumed.
        /// </summary>
        public static string damagedQty {
            get {
                return ResourceManager.GetString("damagedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elementary Department.
        /// </summary>
        public static string elementaryDepartment {
            get {
                return ResourceManager.GetString("elementaryDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environmental.
        /// </summary>
        public static string environmental {
            get {
                return ResourceManager.GetString("environmental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excessive Quntity.
        /// </summary>
        public static string excessiveQty {
            get {
                return ResourceManager.GetString("excessiveQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High School.
        /// </summary>
        public static string highSchool {
            get {
                return ResourceManager.GetString("highSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdose Report.
        /// </summary>
        public static string itemOver {
            get {
                return ResourceManager.GetString("itemOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing items report                                        (lab inventory).
        /// </summary>
        public static string itemPresent {
            get {
                return ResourceManager.GetString("itemPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items Report.
        /// </summary>
        public static string itemReprt {
            get {
                return ResourceManager.GetString("itemReprt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-existent items report.
        /// </summary>
        public static string itemUnAvalable {
            get {
                return ResourceManager.GetString("itemUnAvalable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The possibility of saving.
        /// </summary>
        public static string itm_avalableMethod {
            get {
                return ResourceManager.GetString("itm_avalableMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study unit.
        /// </summary>
        public static string itm_chapter {
            get {
                return ResourceManager.GetString("itm_chapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code.
        /// </summary>
        public static string itm_code {
            get {
                return ResourceManager.GetString("itm_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string itm_department {
            get {
                return ResourceManager.GetString("itm_department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Descrption.
        /// </summary>
        public static string itm_desc {
            get {
                return ResourceManager.GetString("itm_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?Item Is Existing.
        /// </summary>
        public static string itm_isExixting {
            get {
                return ResourceManager.GetString("itm_isExixting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Level.
        /// </summary>
        public static string itm_level {
            get {
                return ResourceManager.GetString("itm_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity present.
        /// </summary>
        public static string itm_presentQty {
            get {
                return ResourceManager.GetString("itm_presentQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School.
        /// </summary>
        public static string itm_schol {
            get {
                return ResourceManager.GetString("itm_schol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search About Item.
        /// </summary>
        public static string itm_search {
            get {
                return ResourceManager.GetString("itm_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugest Quintity.
        /// </summary>
        public static string itm_sugQty {
            get {
                return ResourceManager.GetString("itm_sugQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term.
        /// </summary>
        public static string itm_term {
            get {
                return ResourceManager.GetString("itm_term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to course.
        /// </summary>
        public static string itm_type {
            get {
                return ResourceManager.GetString("itm_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string itm_unit {
            get {
                return ResourceManager.GetString("itm_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level1.
        /// </summary>
        public static string level1 {
            get {
                return ResourceManager.GetString("level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level2.
        /// </summary>
        public static string level2 {
            get {
                return ResourceManager.GetString("level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level3.
        /// </summary>
        public static string level3 {
            get {
                return ResourceManager.GetString("level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level4.
        /// </summary>
        public static string level4 {
            get {
                return ResourceManager.GetString("level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level5.
        /// </summary>
        public static string level5 {
            get {
                return ResourceManager.GetString("level5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level6.
        /// </summary>
        public static string level6 {
            get {
                return ResourceManager.GetString("level6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Department.
        /// </summary>
        public static string middleDepartment {
            get {
                return ResourceManager.GetString("middleDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string note {
            get {
                return ResourceManager.GetString("note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over OR Not.
        /// </summary>
        public static string over {
            get {
                return ResourceManager.GetString("over", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over Quntity.
        /// </summary>
        public static string overQty {
            get {
                return ResourceManager.GetString("overQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physics.
        /// </summary>
        public static string phisics {
            get {
                return ResourceManager.GetString("phisics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational level.
        /// </summary>
        public static string schooldepartment {
            get {
                return ResourceManager.GetString("schooldepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Type.
        /// </summary>
        public static string schooltype {
            get {
                return ResourceManager.GetString("schooltype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sciences.
        /// </summary>
        public static string sience {
            get {
                return ResourceManager.GetString("sience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferable Quntity.
        /// </summary>
        public static string TransferableQty {
            get {
                return ResourceManager.GetString("TransferableQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnValid Quntity.
        /// </summary>
        public static string unValidQty {
            get {
                return ResourceManager.GetString("unValidQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Quntity.
        /// </summary>
        public static string validQty {
            get {
                return ResourceManager.GetString("validQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid OR invalid.
        /// </summary>
        public static string validState {
            get {
                return ResourceManager.GetString("validState", resourceCulture);
            }
        }
    }
}
