//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratories.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LabTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LabTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Laboratories.Web.Resources.LabTable", typeof(LabTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a teacher&apos;s schedule.
        /// </summary>
        public static string crateTeatchertable {
            get {
                return ResourceManager.GetString("crateTeatchertable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Registered Classes.
        /// </summary>
        public static string lessonCount {
            get {
                return ResourceManager.GetString("lessonCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Number Of Classes.
        /// </summary>
        public static string lessonCountActual {
            get {
                return ResourceManager.GetString("lessonCountActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesson Number.
        /// </summary>
        public static string lessonNum {
            get {
                return ResourceManager.GetString("lessonNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month Numberr.
        /// </summary>
        public static string monthNumberr {
            get {
                return ResourceManager.GetString("monthNumberr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Number Of Classes.
        /// </summary>
        public static string teacherMovment {
            get {
                return ResourceManager.GetString("teacherMovment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher Name.
        /// </summary>
        public static string teacherName {
            get {
                return ResourceManager.GetString("teacherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week Number.
        /// </summary>
        public static string weekNumber {
            get {
                return ResourceManager.GetString("weekNumber", resourceCulture);
            }
        }
    }
}
