//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratories.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Report {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Report() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Laboratories.Web.Resources.Report", typeof(Report).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose The Report By.
        /// </summary>
        public static string choisReportType {
            get {
                return ResourceManager.GetString("choisReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Items.
        /// </summary>
        public static string displayItem {
            get {
                return ResourceManager.GetString("displayItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Items.
        /// </summary>
        public static string downloadItem {
            get {
                return ResourceManager.GetString("downloadItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excessive Qty Report.
        /// </summary>
        public static string excessiveQtyReport {
            get {
                return ResourceManager.GetString("excessiveQtyReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General furniture Report.
        /// </summary>
        public static string generalBasicReport {
            get {
                return ResourceManager.GetString("generalBasicReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Item Report.
        /// </summary>
        public static string generalItemReport {
            get {
                return ResourceManager.GetString("generalItemReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Wanted and Can Avalable.
        /// </summary>
        public static string item_wantedCanavalable {
            get {
                return ResourceManager.GetString("item_wantedCanavalable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Wanted and Can Required.
        /// </summary>
        public static string item_wantedRequired {
            get {
                return ResourceManager.GetString("item_wantedRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item By Available Method.
        /// </summary>
        public static string ItemByavailableMethod {
            get {
                return ResourceManager.GetString("ItemByavailableMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Byi Chapter.
        /// </summary>
        public static string ItemByChapter {
            get {
                return ResourceManager.GetString("ItemByChapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item By Department.
        /// </summary>
        public static string ItemByDepartment {
            get {
                return ResourceManager.GetString("ItemByDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item By level.
        /// </summary>
        public static string ItemBylevel {
            get {
                return ResourceManager.GetString("ItemBylevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item By present Quintity.
        /// </summary>
        public static string ItemBypresentQty {
            get {
                return ResourceManager.GetString("ItemBypresentQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item By Sugest Quintity.
        /// </summary>
        public static string ItemBySugQty {
            get {
                return ResourceManager.GetString("ItemBySugQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item By Unit.
        /// </summary>
        public static string ItemByUnit {
            get {
                return ResourceManager.GetString("ItemByUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Existing.
        /// </summary>
        public static string ItemExisting {
            get {
                return ResourceManager.GetString("ItemExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scdual Report.
        /// </summary>
        public static string scdualReport {
            get {
                return ResourceManager.GetString("scdualReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Report.
        /// </summary>
        public static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Custody.
        /// </summary>
        public static string TransferCustody {
            get {
                return ResourceManager.GetString("TransferCustody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer From.
        /// </summary>
        public static string transferfrom {
            get {
                return ResourceManager.GetString("transferfrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to transfer From  Scool To Another.
        /// </summary>
        public static string transferfromscooltoanother {
            get {
                return ResourceManager.GetString("transferfromscooltoanother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer To.
        /// </summary>
        public static string transferTo {
            get {
                return ResourceManager.GetString("transferTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un Valid Items .
        /// </summary>
        public static string UnValidItemReport {
            get {
                return ResourceManager.GetString("UnValidItemReport", resourceCulture);
            }
        }
    }
}
