//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratories.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StudentRates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StudentRates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Laboratories.Web.Resources.StudentRates", typeof(StudentRates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis Of The Results.
        /// </summary>
        public static string AnalysisOfTheResults {
            get {
                return ResourceManager.GetString("AnalysisOfTheResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Name.
        /// </summary>
        public static string courseName {
            get {
                return ResourceManager.GetString("courseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree.
        /// </summary>
        public static string degree {
            get {
                return ResourceManager.GetString("degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Student.
        /// </summary>
        public static string displayStudent {
            get {
                return ResourceManager.GetString("displayStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Date.
        /// </summary>
        public static string examDate {
            get {
                return ResourceManager.GetString("examDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Name.
        /// </summary>
        public static string examName {
            get {
                return ResourceManager.GetString("examName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exams.
        /// </summary>
        public static string exams {
            get {
                return ResourceManager.GetString("exams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exams Name.
        /// </summary>
        public static string examsname {
            get {
                return ResourceManager.GetString("examsname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grading Monitoring.
        /// </summary>
        public static string gradingMonitoring {
            get {
                return ResourceManager.GetString("gradingMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Record.
        /// </summary>
        public static string levelRecord {
            get {
                return ResourceManager.GetString("levelRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string rate {
            get {
                return ResourceManager.GetString("rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id number.
        /// </summary>
        public static string studentId {
            get {
                return ResourceManager.GetString("studentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StudentName.
        /// </summary>
        public static string studentName {
            get {
                return ResourceManager.GetString("studentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students Number.
        /// </summary>
        public static string studentNumber {
            get {
                return ResourceManager.GetString("studentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Rates.
        /// </summary>
        public static string studentRates {
            get {
                return ResourceManager.GetString("studentRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string students {
            get {
                return ResourceManager.GetString("students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Course.
        /// </summary>
        public static string studyCourse {
            get {
                return ResourceManager.GetString("studyCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher Name.
        /// </summary>
        public static string teacherName {
            get {
                return ResourceManager.GetString("teacherName", resourceCulture);
            }
        }
    }
}
