// <auto-generated />
namespace Laboratories.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class editMobv2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editMobv2));
        
        string IMigrationMetadata.Id
        {
            get { return "202207281251166_editMobv2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
