// <auto-generated />
namespace Laboratories.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddLevelToCourse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddLevelToCourse));
        
        string IMigrationMetadata.Id
        {
            get { return "202304090809215_AddLevelToCourse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
